// actionType.js
export const BACKORDER_CREATE_REQUEST = "BACKORDER_CREATE_REQUEST";
export const BACKORDER_CREATE_SUCCESS = "BACKORDER_CREATE_SUCCESS";
export const BACKORDER_CREATE_FAILURE = "BACKORDER_CREATE_FAILURE";

export const BACKORDER_FETCH_REQUEST = "BACKORDER_FETCH_REQUEST";
export const BACKORDER_FETCH_SUCCESS = "BACKORDER_FETCH_SUCCESS";
export const BACKORDER_FETCH_FAILURE = "BACKORDER_FETCH_FAILURE";